name: python3.10-rl-sumo-gpu
channels:

- conda-forge

- defaults

dependencies:

# Base

- python=3.10.19

- pip>=24.0

- setuptools=68.2.2

- wheel=0.41.2

# SciPy stack via conda (works well on Windows)

- numpy=1.26.4

- pandas=1.5.3

# Options

- ca-certificates

- openssl

- pip:

# Use extra-index for PyTorch CUDA, DO NOT overwrite default index

- --extra-index-url https://download.pytorch.org/whl/cu121

# PyTorch CUDA 12.1

- torch==2.4.1+cu121

- torchvision==0.19.1+cu121

- torchaudio==2.4.1+cu121

# RLlib and deps compatibility

- ray[rllib]==2.9.3

- gymnasium==0.28.1

- pettingzoo==1.24.3

# SUMO-RL

- sumo-rl==1.4.5

# CHANGE PYARROW TO PIP to avoid OpenSSL conflicts

- pyarrow==6.0.1
